// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicHello: typeof import('./../components/Basic/Hello.vue')['default']
    BasicWorld: typeof import('./../components/Basic/World.vue')['default']
    DarkToggle: typeof import('./../components/DarkToggle.vue')['default']
    IconCustomFace: typeof import('~icons/custom/face')['default']
    IconCustomMoon: typeof import('~icons/custom/moon')['default']
    IconCustomSun: typeof import('~icons/custom/sun')['default']
    IconMdiGoogleDownasaur: typeof import('~icons/mdi/google-downasaur')['default']
    PageFooter: typeof import('./../components/PageFooter.vue')['default']
  }
}

export {}
